declare
 I NUMBER ;
 BEGIN
    SELECT COUNT(1)  INTO I
    FROM USER_INDEXES AU WHERE AU.TABLE_OWNER = UPPER ('OWNER_NAME')
    AND AU.TABLE_NAME = UPPER ('TABLE_NAME')
    AND AU.INDEX_NAME = UPPER ('INDEX_NAME');
    IF I > 0 THEN
    BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX INDEX_NAME';
        EXECUTE IMMEDIATE 'CREATE INDEX OWNER_NAME.INDEX_NAME ON OWNER_NAME.TABLE_NAME(COLUMN ASC,COLUNM ASC) INITRANS 16';
    END;
    ELSE
    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX OWNER_NAME.INDEX_NAME ON OWNER_NAME.TABLE_NAME(COLUMN ASC,COLUNM ASC) INITRANS 16';
    END;
 END
/